name: Juju Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: "Configure LXD"
        run: |        
          sudo adduser $USER lxd
          newgrp lxd        
          sudo lxd init --auto
          sudo lxc network set lxdbr0 ipv6.address none        
          sudo chmod a+wr /var/snap/lxd/common/lxd/unix.socket

      - name: Install Juju
        run: |
          sudo snap install juju --channel=2.9/stable --classic
          # sudo snap install juju-wait --classic

      - name: Bootstrap Juju
        run: |
          juju bootstrap localhost

      - name: Deploy PostgreSQL
        run: |
          juju deploy postgresql

      - name: Deploy Nextcloud
        run: |
          juju deploy nextcloud --channel edge --series jammy

      - name: Relate Nextcloud and PostgreSQL
        run: |
          juju relate nextcloud:database postgresql
