name: Juju Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3


      - name: Setup operator environment (with lxd)
        uses: charmed-kubernetes/actions-operator@main
        with:
          provider: lxd

      - name: Deploy PostgreSQL
        run: |
          juju deploy postgresql

      - name: Deploy Nextcloud
        run: |
          juju deploy nextcloud --channel edge --series jammy

      - name: Relate Nextcloud and PostgreSQL
        run: |
          juju relate nextcloud:database postgresql

      - name: Wait for Nextcloud status to become active
        run: |
          for i in {1..90}; do
            status=$(juju status --format=json | jq -r '.applications.nextcloud."application-status".current')
            if [[ "$status" == "active" ]]; then
              echo "Nextcloud deployment is active!"
              exit 0
            else:
              echo "Waiting for nextcloud to be active...($i/30)"
            fi
            sleep 10
          done
          echo "Nextcloud deployment did not become active within 15 minutes."
          exit 1
