name: Juju Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: "Configure LXD"
        run: |        
          sudo adduser $USER lxd
          newgrp lxd        
          sudo lxd init --auto
          # Disable IPv6 for the LXD bridge interface
          sudo sed -i 's/^#net.ipv6.conf.default.disable_ipv6.*/net.ipv6.conf.default.disable_ipv6 = 1/' /etc/sysctl.conf
          sudo sed -i 's/^#net.ipv6.conf.all.disable_ipv6.*/net.ipv6.conf.all.disable_ipv6 = 1/' /etc/sysctl.conf
          sudo sysctl -p

          # Disable IPv6 for the LXD default profile
          sudo lxc profile device set default eth0 ipv6.address none

          sudo systemctl restart snap.lxd.daemon
          sudo chmod a+wr /var/snap/lxd/common/lxd/unix.socket
          

      - name: Install Juju
        run: |
          sudo snap install juju --channel=2.9/stable --classic
          # sudo snap install juju-wait --classic

      - name: Bootstrap Juju
        run: |
          juju bootstrap localhost

      - name: Deploy PostgreSQL
        run: |
          juju deploy postgresql

      - name: Deploy Nextcloud
        run: |
          juju deploy nextcloud --channel edge --series jammy

      - name: Relate Nextcloud and PostgreSQL
        run: |
          juju relate nextcloud:database postgresql

      - name: Wait for Nextcloud status to become active
        run: |
          for i in {1..30}; do
            status=$(juju status --format=json | jq -r '.applications.nextcloud.status.current')
            if [[ "$status" == "active" ]]; then
              echo "Nextcloud deployment is active!"
              exit 0
            fi
            sleep 10
          done
          echo "Nextcloud deployment did not become active within 5 minutes."
          exit 1
